routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\DriverController;
use App\Http\Controllers\VehicleController;
use App\Http\Controllers\StationController;
use App\Http\Controllers\TripController;
use App\Http\Controllers\CompanyController;
use App\Http\Controllers\ScreenController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes(['register' => false]);

Route::get('/import', [App\Http\Controllers\ImportController::class, 'uploadContent']);
Route::get('/dashboard', [App\Http\Controllers\HomeController::class, 'index'])->name('dashboard');

 


Route::group(['prefix' => 'driver','as'=>'driver.'], function () {
    Route::get('/', [DriverController::class, 'index'])->name('index');
    Route::post('/list', [DriverController::class, 'list'])->name('list');
    Route::get('/create', [DriverController::class, 'create'])->name('create');
    Route::get('/show/{id}', [DriverController::class, 'show'])->name('show');
    Route::get('/edit/{id}', [DriverController::class, 'edit'])->name('edit');

    Route::post('/store', [DriverController::class, 'store'])->name('store');
    Route::post('/update/{id}', [DriverController::class, 'update'])->name('update');
    Route::post('/delete/{id}', [DriverController::class, 'destroy'])->name('destroy');
    
});

Route::group(['prefix' => 'vehicles','as'=>'vehicles.'], function () {
    Route::get('/', [VehicleController::class, 'index'])->name('index');
    Route::post('/list', [VehicleController::class, 'list'])->name('list');
    Route::get('/create', [VehicleController::class, 'create'])->name('create');
    Route::get('/show/{id}', [VehicleController::class, 'show'])->name('show');
    Route::get('/edit/{id}', [VehicleController::class, 'edit'])->name('edit');

    Route::post('/store', [VehicleController::class, 'store'])->name('store');
    Route::post('/update/{id}', [VehicleController::class, 'update'])->name('update');
    Route::post('/delete/{id}', [VehicleController::class, 'destroy'])->name('destroy');
});

Route::group(['prefix' => 'stations','as'=>'stations.'], function () {
    Route::get('/', [StationController::class, 'index'])->name('index');
    Route::post('/list', [StationController::class, 'list'])->name('list');
    Route::get('/create', [StationController::class, 'create'])->name('create');
    Route::get('/show/{id}', [StationController::class, 'show'])->name('show');
    Route::get('/edit/{id}', [StationController::class, 'edit'])->name('edit');

    Route::post('/store', [StationController::class, 'store'])->name('store');
    Route::post('/update/{id}', [StationController::class, 'update'])->name('update');
    Route::post('/delete/{id}', [StationController::class, 'destroy'])->name('destroy');
});

Route::group(['prefix' => 'trips','as'=>'trips.'], function () {
    Route::get('/', [TripController::class, 'index'])->name('index');
    Route::post('/list', [TripController::class, 'list'])->name('list');
    Route::get('/create', [TripController::class, 'create'])->name('create');
    Route::get('/show/{id}', [TripController::class, 'show'])->name('show');
    Route::get('/edit/{id}', [TripController::class, 'edit'])->name('edit');

    Route::post('/store', [TripController::class, 'store'])->name('store');
    Route::post('/update/{id}', [TripController::class, 'update'])->name('update');
    Route::post('/delete/{id}', [TripController::class, 'destroy'])->name('destroy');
});

Route::group(['prefix' => 'companies','as'=>'companies.'], function () {
    Route::get('/', [CompanyController::class, 'index'])->name('index');
    Route::post('/list', [CompanyController::class, 'list'])->name('list');
    Route::get('/create', [CompanyController::class, 'create'])->name('create');
    Route::get('/show/{id}', [CompanyController::class, 'show'])->name('show');
    Route::get('/edit/{id}', [CompanyController::class, 'edit'])->name('edit');

    Route::post('/store', [CompanyController::class, 'store'])->name('store');
    Route::post('/update/{id}', [CompanyController::class, 'update'])->name('update');
    Route::post('/delete/{id}', [CompanyController::class, 'destroy'])->name('destroy');
});

Route::group(['prefix' => 'screens','as'=>'screens.'], function () {
    Route::get('/', [ScreenController::class, 'index'])->name('index');
    Route::post('/list', [ScreenController::class, 'list'])->name('list');
    Route::get('/create', [ScreenController::class, 'create'])->name('create');
    Route::get('/show/{id}', [ScreenController::class, 'show'])->name('show');
    Route::get('/edit/{id}', [ScreenController::class, 'edit'])->name('edit');

    Route::post('/store', [ScreenController::class, 'store'])->name('store');
    Route::post('/update/{id}', [ScreenController::class, 'update'])->name('update');
    Route::post('/delete/{id}', [ScreenController::class, 'destroy'])->name('destroy');
});

app/Models/Station.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Station extends Model
{
    use HasFactory;
    
    protected $fillable = [
        "stationCode",
        "arabicName",
        "englishName",
        "latitude",
        "longitude",
        "cityCode",
        "stationStatus",
        "email",
        "phone",
        "phoneExtension",
        "managerPhone",
    ];
}

app/Http/Controllers/StationController.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use App\Models\Station;
use App\Models\City;
use Illuminate\Http\Request;
use Yajra\DataTables\DataTables;
use Exception;

class StationController extends Controller
{

    public function index()
    {
        return view('stations.index');
    }

    
    public function list(DataTables $datatables,Request $request){
        // $user = auth()->user();
        $query = \DB::table('stations');
        /*if(!empty($user->region) && strtolower($user->region) != 'all') {
            $query->whereRaw('(region) = ?',["{$user->region}"]);
        }
        if(!empty($user->territory) && strtolower($user->territory) != 'all') {
            $query->whereRaw('(territory) = ?',["{$user->territory}"]);
        }*/
        // return $datatables->eloquent(HCP::query())
        return   $datatables->of($query)
            ->addColumn('action',function ($table) {
                return view('tables.action',['table'=>$table,'prefix'=>'stations']);
            })
            ->rawColumns(['action'])
            ->toJson();
    }



    public function create()
    {
        $cities = City::select('englishName','code')->get();
        $companies = [(object)['id'=> "f91ceb6c-c59f-4b26-ab31-d9654d1cdbe5",'name'=> 'f91ceb6c-c59f-4b26-ab31-d9654d1cdbe5']];
        $activities = config('constants.activities');
        return view('stations.create', compact('companies','activities','cities'));
    }

    public function store(Request $request)
    {
        $data = $this->getData($request);
        try {
            
			$station_data = ["stationCode"=> $data['stationCode'],"arabicName" => $data['arabicName'],"englishName"=> $data['englishName'],"latitude"=> (float)$data['latitude'],"longitude"=> (float)$data['longitude'],"cityCode"=> $data['cityCode'],"stationStatus"=> $data['stationStatus'],"email"=> $data['email'],"phone"=> $data['phone'],"phoneExtension"=> $data['phoneExtension'],"managerPhone"=> $data['managerPhone']];
			$json_data = json_encode($station_data);
			
			echo $json_data;
			$curl = curl_init();

			curl_setopt_array($curl, array(
			  CURLOPT_URL => 'https://wasl.tga.gov.sa/api/tracking/v1/station',
			  CURLOPT_RETURNTRANSFER => true,
			  CURLOPT_ENCODING => '',
			  CURLOPT_MAXREDIRS => 10,
			  CURLOPT_TIMEOUT => 0,
			  CURLOPT_FOLLOWLOCATION => true,
			  CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
			  CURLOPT_CUSTOMREQUEST => 'POST',
			  CURLOPT_POSTFIELDS => $json_data,
			  CURLOPT_HTTPHEADER => array(
				'x-api-key: 1190c6bb-ea86-4302-bcbb-e426a279ce0b',
				'Content-Type: application/json'
			  ),
			));

			$response = curl_exec($curl);

			curl_close($curl);
			$result = json_decode($response);
			
			if($result->success){
				Station::create($data);
				return redirect()->route('stations.index')
                             ->with('success_message', 'Station was successfully added.');
			} else {
				return back()->withInput()
                         ->withErrors(['unexpected_error' => 'Unexpected error occurred while trying to process your request.']);
			}
        } catch (Exception $exception) {

            return back()->withInput()
                         ->withErrors(['unexpected_error' => 'Unexpected error occurred while trying to process your request.']);
        }
    }

    /**
     * Display the specified labor item.
     *
     * @param int $id
     *
     * @return Illuminate\View\View
     */
    public function show($id)
    {
        $station = Station::findOrFail($id);

        return view('stations.show', compact('station'));
    }

    /**
     * Show the form for editing the specified labor item.
     *
     * @param int $id
     *
     * @return Illuminate\View\View
     */
    public function edit($id)
    {
        $station =  Station::findOrFail($id);
        $cities = City::select('englishName','code')->get();

        $companies = [(object)['id'=> "f91ceb6c-c59f-4b26-ab31-d9654d1cdbe5",'name'=> 'f91ceb6c-c59f-4b26-ab31-d9654d1cdbe5']];
        $activities = config('constants.activities');
        return view('stations.edit', compact('station','companies','activities','cities'));
    }

    /**
     * Update the specified labor item in the storage.
     *
     * @param  int $id
     * @param Illuminate\Http\Request $request
     *
     * @return Illuminate\Http\RedirectResponse | Illuminate\Routing\Redirector
     */
    public function update($id, Request $request)
    {
        $data = $this->getData($request);
        try {
            $statation =  Station::findOrFail($id);
			$station_data = ["stationCode"=> $data['stationCode'],"arabicName" => $data['arabicName'],"englishName"=> $data['englishName'],"latitude"=> (float)$data['latitude'],"longitude"=> (float)$data['longitude'],"cityCode"=> $data['cityCode'],"stationStatus"=> $data['stationStatus'],"email"=> $data['email'],"phone"=> $data['phone'],"phoneExtension"=> $data['phoneExtension'],"managerPhone"=> $data['managerPhone']];
			$json_data = json_encode($station_data);
			$curl = curl_init();

			curl_setopt_array($curl, array(
			  CURLOPT_URL => 'https://wasl.tga.gov.sa/api/tracking/v1/station',
			  CURLOPT_RETURNTRANSFER => true,
			  CURLOPT_ENCODING => '',
			  CURLOPT_MAXREDIRS => 10,
			  CURLOPT_TIMEOUT => 0,
			  CURLOPT_FOLLOWLOCATION => true,
			  CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
			  CURLOPT_CUSTOMREQUEST => 'POST',
			  CURLOPT_POSTFIELDS => $json_data,
			  CURLOPT_HTTPHEADER => array(
				'x-api-key: 1190c6bb-ea86-4302-bcbb-e426a279ce0b',
				'Content-Type: application/json'
			  ),
			));

			$response = curl_exec($curl);

			curl_close($curl);
			$result = json_decode($response);
			if($result->success){
				
				$statation->update($data);

				return redirect()->route('stations.index')
                             ->with('success_message', 'Station was successfully updated.');
			} else{
				return back()->withInput()
                         ->withErrors(['unexpected_error' => 'Unexpected error occurred while trying to process your request.']);
			}

        } catch (Exception $exception) {

            return back()->withInput()
                         ->withErrors(['unexpected_error' => 'Unexpected error occurred while trying to process your request.']);
        }
    }

    /**
     * Remove the specified labor item from the storage.
     *
     * @param  int $id
     *
     * @return Illuminate\Http\RedirectResponse | Illuminate\Routing\Redirector
     */
    public function destroy($id)
    {
        try {
            $driver = Station::findOrFail($id);
            $driver->delete();

            return redirect()->route('stations.index')
                             ->with('success_message', 'Labor Item was successfully deleted.');

        } catch (Exception $exception) {

            return back()->withInput()
                         ->withErrors(['unexpected_error' => 'Unexpected error occurred while trying to process your request.']);
        }
    }


    /**
     * Get the request's data from the request.
     *
     * @param Illuminate\Http\Request\Request $request
     * @return array
     */
    protected function getData(Request $request)
    {
        $rules = [
            'stationCode' => 'required',
            'arabicName' => 'required',
            'englishName' => 'required',
            'latitude' => 'required',
            'longitude' => 'required',
            'cityCode' => 'required',
            'stationStatus' => 'required',
            'email' => 'required',
            'phone' => 'required',
            'phoneExtension' => 'required',
            'managerPhone' => 'required',
        ];
        $data = $request->validate($rules);
        
        return $data;
    }

}

resources/views/stations/create.blade.php
@extends('layouts.master')
@section('content')
<div class="container-fluid">
	<div class="row">
		<div class="col-lg-12">
			<div class="breadcrumb-main user-member justify-content-sm-between ">
				<div class=" d-flex flex-wrap justify-content-center breadcrumb-main__wrapper">
					<div class="d-flex align-items-center user-member__title justify-content-center mr-sm-25">
						<h4 class="text-capitalize fw-500 breadcrumb-title">Add Station</h4>
					</div>
				</div>
				 <div class="action-btn">
                        <a href="{{ route('stations.index') }}" class="btn px-15 btn-primary" >Cancel</a>
                 </div>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-lg-12">
			<!-- Start: product page -->
			<div class="global-shadow border px-sm-30 py-sm-50 px-0 py-20 bg-white radius-xl w-100 mb-40">
				<div class="row  ">
					<div class="col-xl-12 col-lg-10">
						<div class="mx-sm-30 mx-20 ">
							<!-- Start: card -->
							<!-- <div class="card add-product p-sm-30 p-20 mb-30">
									<div class="card-body p-0">
										<div class="card-header">
											<h6 class="fw-500">Add Product</h6>
										</div> -->
										<!-- Start: card body -->
										<div class="add-product__body px-sm-40 px-20">
											<form method="POST" action="{{ route('stations.store') }}" accept-charset="UTF-8" id="create_user_form" name="create_user_form" class="form-horizontal" enctype="multipart/form-data">
													{{ csrf_field() }}
													@include ('stations.form', ['station' => null])
											</form>
										</div>
								<!-- </div>
							</div> -->
					
						</div>
					</div>
				</div>
			</div>
			<!-- End: Product page -->
		</div>
		<!-- ends: col-lg-12 -->
	</div>
</div>
@endsection

resources/views/stations/edit.blade.php
@extends('layouts.master')
@section('content')
<div class="container-fluid">
	<div class="row">
		<div class="col-lg-12">
			<div class="breadcrumb-main user-member justify-content-sm-between ">
				<div class=" d-flex flex-wrap justify-content-center breadcrumb-main__wrapper">
					<div class="d-flex align-items-center user-member__title justify-content-center mr-sm-25">
						<h4 class="text-capitalize fw-500 breadcrumb-title">Edit Station</h4>
					</div>
				</div>
				 <div class="action-btn">
                        <a href="{{ route('stations.index') }}" class="btn px-15 btn-primary" >Cancel</a>
                 </div>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-lg-12">
			<!-- Start: product page -->
			<div class="global-shadow border px-sm-30 py-sm-50 px-0 py-20 bg-white radius-xl w-100 mb-40">
				<div class="row  ">
					<div class="col-xl-12 col-lg-10">
						<div class="mx-sm-30 mx-20 ">
							<!-- Start: card -->
							<!-- <div class="card add-product p-sm-30 p-20 mb-30">
									<div class="card-body p-0">
										<div class="card-header">
											<h6 class="fw-500">Add Product</h6>
										</div> -->
										<!-- Start: card body -->
										<div class="add-product__body px-sm-40 px-20">
											<form method="POST" action="{{ route('stations.update',$station->id) }}" accept-charset="UTF-8" id="create_user_form" name="create_user_form" class="form-horizontal" enctype="multipart/form-data">
													{{ csrf_field() }}
													@include ('stations.form', ['station' => $station])
											</form>
										</div>
								<!-- </div>
							</div> -->
					
						</div>
					</div>
				</div>
			</div>
			<!-- End: Product page -->
		</div>
		<!-- ends: col-lg-12 -->
	</div>
</div>
@endsection

resources/views/stations/form.blade.php
<div class="form-basic">
    <div class="col-md-12" id="message">
        @if ($message = Session::get('error'))
        <div class="alert alert-danger">
          <p>{{ $message }}</p>
        </div>
        @endif
    </div>  
	@error('unexpected_error')

			<span class="invalid-feedback" role="alert">
				<strong>{{ $message }}</strong>
			</span>
		@enderror

	<div class="form-group">
		<label for="name1">Station Code</label>
		<input type="text" id="stationCode" name="stationCode" class="form-control" placeholder="Enter Station Code" value="{{old('stationCode', optional($station)->stationCode)}}" > 
		@error('stationCode')
			<span class="invalid-feedback" role="alert">
				<strong>{{ $message }}</strong>
			</span>
		@enderror
	</div> 

	<div class="form-group">
		<label for="name1">Arabic Name</label>
		<input type="text" id="arabicName" name="arabicName" class="form-control" placeholder="Enter Arabic Name" value="{{old('arabicName', optional($station)->arabicName)}}" > 
		@error('arabicName')
			<span class="invalid-feedback" role="alert">
				<strong>{{ $message }}</strong>
			</span>
		@enderror
	</div> 
	<div class="form-group">
		<label for="name1">English Name</label>
		<input type="text" id="englishName" name="englishName" class="form-control" placeholder="Enter English Name" value="{{old('englishName', optional($station)->englishName)}}" > 
		@error('englishName')
			<span class="invalid-feedback" role="alert">
				<strong>{{ $message }}</strong>
			</span>
		@enderror
	</div> 
 

	
	<div class="form-group">
		<label for="name1">Latitude</label>
		<input type="text" id="latitude" name="latitude" class="form-control" placeholder="Enter Latitude" value="{{old('latitude', optional($station)->latitude)}}" > 
		@error('latitude')
			<span class="invalid-feedback" role="alert">
				<strong>{{ $message }}</strong>
			</span>
		@enderror
	</div> 

	<div class="form-group">
		<label for="name1">Longitude</label>
		<input type="text" id="longitude" name="longitude" class="form-control" placeholder="Enter Longitude" value="{{old('longitude', optional($station)->longitude)}}" > 
		@error('longitude')
			<span class="invalid-feedback" role="alert">
				<strong>{{ $message }}</strong>
			</span>
		@enderror
	</div> 
 
 
	<div class="form-group">
		<div class="countryOption">
			<label for="countryOption">City Code </label>
			<select class="js-example-basic-single js-states form-control" id="cityCode" name="cityCode" >
				<option value="" style="display:none;">Select City</option>
                @foreach ($cities as $value)
                    <option value="{{ $value->code }}"  {{ ( $value->code == old('cityCode', optional($station)->cityCode)) ? 'selected' : '' }}>{{$value->englishName}}</option>
                @endforeach
			</select>
			@error('cityCode')
				<span class="invalid-feedback" role="alert">
					<strong>{{ $message }}</strong>
				</span>
			@enderror
		</div>
	</div>

	<div class="form-group">
		<div class="countryOption">
			<label for="countryOption"> Status </label>
			<select class="js-example-basic-single js-states form-control" id="stationStatus" name="stationStatus" >
				<option value="" style="display:none;">Select Status</option>
                @foreach (['ACTIVE','INACTIVE'] as $value)
                    <option value="{{ $value }}"  {{ ( $value == old('stationStatus',optional($station)->stationStatus)) ? 'selected' : '' }}>{{$value}}</option>
                @endforeach
			</select>
			@error('stationStatus')
				<span class="invalid-feedback" role="alert">
					<strong>{{ $message }}</strong>
				</span>
			@enderror
		</div>
	</div>



	<div class="form-group">
		<label for="name1">Email</label>
		<input type="text" id="email" name="email" class="form-control" placeholder="Enter Email" value="{{old('email', optional($station)->email)}}" > 
		@error('email')
			<span class="invalid-feedback" role="alert">
				<strong>{{ $message }}</strong>
			</span>
		@enderror
	</div> 
 


	<div class="form-group">
		<label for="name1">Phone</label>
		<input type="text" id="phone" name="phone" class="form-control" placeholder="Enter Phone" value="{{old('phone', optional($station)->phone)}}" > 
		@error('phone')
			<span class="invalid-feedback" role="alert">
				<strong>{{ $message }}</strong>
			</span>
		@enderror
	</div> 
 
	<div class="form-group">
		<label for="name1">Phone extension</label>
		<input type="text" id="phoneExtension" name="phoneExtension" class="form-control" placeholder="Enter Phone extension" value="{{old('phoneExtension', optional($station)->phoneExtension)}}" > 
		@error('phoneExtension')
			<span class="invalid-feedback" role="alert">
				<strong>{{ $message }}</strong>
			</span>
		@enderror
	</div> 
 

	<div class="form-group">
		<label for="name1">Manager phone</label>
		<input type="text" id="managerPhone" name="managerPhone" class="form-control" placeholder="Enter Manager phone" value="{{old('managerPhone', optional($station)->managerPhone)}}" > 
		@error('managerPhone')
			<span class="invalid-feedback" role="alert">
				<strong>{{ $message }}</strong>
			</span>
		@enderror
	</div> 
  
	<!-- Start: button group -->
	<div class="button-group add-product-btn d-flex justify-content-end mt-40">
		<button class="btn btn-light btn-default btn-squared fw-400 text-capitalize"> <a  href="{{ route('stations.index') }}"> cancel</a></button>
		<button class="btn btn-primary btn-default btn-squared text-capitalize">Save</button>
	</div>
	<!-- End: button group -->
</div>

resources/views/stations/show.blade.php
@extends('layouts.master')
@section('content')
<div class="container-fluid">
	<div class="row">
		<div class="col-lg-12">
			<div class="breadcrumb-main user-member justify-content-sm-between ">
				<div class=" d-flex flex-wrap justify-content-center breadcrumb-main__wrapper">
					<div class="d-flex align-items-center user-member__title justify-content-center mr-sm-25">
						<h4 class="text-capitalize fw-500 breadcrumb-title">Driver Detail</h4>
					</div>
				</div>
				 <div class="action-btn">
                <a href="{{ route('driver.index') }}" class="btn px-15 btn-primary" >Driver List</a>
         </div>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-lg-12">
			<!-- Start: product page -->
			<div class="global-shadow border px-sm-15 py-sm-30 px-0 py-20 bg-white radius-xl w-100 mb-40">
				<div class="row  ">
					<div class="col-xl-12 col-lg-10">
						<div class="mx-sm-30 mx-20 ">
					 
							<div class=" "> 
								
								 <div class="div mb-3">
				                    <h6>Station Code</h6>
				                    <span>{{ $station->stationCode }}</span>
				                </div> 
						 
								 <div class="div mb-3">
				                    <h6>Arabic Name</h6>
				                    <span>{{ $station->arabicName }}</span>
				                </div> 
						 
								 <div class="div mb-3">
				                    <h6>English Name</h6>
				                    <span>{{ $station->englishName }}</span>
				                </div> 
						 
								 <div class="div mb-3">
				                    <h6>Latitude</h6>
				                    <span>{{ $station->latitude }}</span>
				                </div> 
						 
								 <div class="div mb-3">
				                    <h6>Longitude</h6>
				                    <span>{{ $station->longitude }}</span>
				                </div> 
						 
								 <div class="div mb-3">
				                    <h6>City Code</h6>
				                    <span>{{ $station->cityCode }}</span>
				                </div> 
						 
								 <div class="div mb-3">
				                    <h6>Station Status</h6>
				                    <span>{{ $station->stationStatus }}</span>
				                </div> 
						 
								 <div class="div mb-3">
				                    <h6>Email</h6>
				                    <span>{{ $station->email }}</span>
				                </div> 
						 
								 <div class="div mb-3">
				                    <h6>Phone</h6>
				                    <span>{{ $station->phone }}</span>
				                </div> 
						 
								 <div class="div mb-3">
				                    <h6>Phone Extension</h6>
				                    <span>{{ $station->phoneExtension }}</span>
				                </div> 
						 
								 <div class="div mb-3">
				                    <h6>Manager Phone</h6>
				                    <span>{{ $station->managerPhone }}</span>
				                </div> 
						 
							</div>
							 
					
						</div>
					</div>
				</div>
			</div>
			<!-- End: Product page -->
		</div>
		<!-- ends: col-lg-12 -->
	</div>
</div>
@endsection

 