routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\DriverController;
use App\Http\Controllers\VehicleController;
use App\Http\Controllers\StationController;
use App\Http\Controllers\TripController;
use App\Http\Controllers\CompanyController;
use App\Http\Controllers\ScreenController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes(['register' => false]);

Route::get('/import', [App\Http\Controllers\ImportController::class, 'uploadContent']);
Route::get('/dashboard', [App\Http\Controllers\HomeController::class, 'index'])->name('dashboard');

 


Route::group(['prefix' => 'driver','as'=>'driver.'], function () {
    Route::get('/', [DriverController::class, 'index'])->name('index');
    Route::post('/list', [DriverController::class, 'list'])->name('list');
    Route::get('/create', [DriverController::class, 'create'])->name('create');
    Route::get('/show/{id}', [DriverController::class, 'show'])->name('show');
    Route::get('/edit/{id}', [DriverController::class, 'edit'])->name('edit');

    Route::post('/store', [DriverController::class, 'store'])->name('store');
    Route::post('/update/{id}', [DriverController::class, 'update'])->name('update');
    Route::post('/delete/{id}', [DriverController::class, 'destroy'])->name('destroy');
    
});

Route::group(['prefix' => 'vehicles','as'=>'vehicles.'], function () {
    Route::get('/', [VehicleController::class, 'index'])->name('index');
    Route::post('/list', [VehicleController::class, 'list'])->name('list');
    Route::get('/create', [VehicleController::class, 'create'])->name('create');
    Route::get('/show/{id}', [VehicleController::class, 'show'])->name('show');
    Route::get('/edit/{id}', [VehicleController::class, 'edit'])->name('edit');

    Route::post('/store', [VehicleController::class, 'store'])->name('store');
    Route::post('/update/{id}', [VehicleController::class, 'update'])->name('update');
    Route::post('/delete/{id}', [VehicleController::class, 'destroy'])->name('destroy');
});

Route::group(['prefix' => 'stations','as'=>'stations.'], function () {
    Route::get('/', [StationController::class, 'index'])->name('index');
    Route::post('/list', [StationController::class, 'list'])->name('list');
    Route::get('/create', [StationController::class, 'create'])->name('create');
    Route::get('/show/{id}', [StationController::class, 'show'])->name('show');
    Route::get('/edit/{id}', [StationController::class, 'edit'])->name('edit');

    Route::post('/store', [StationController::class, 'store'])->name('store');
    Route::post('/update/{id}', [StationController::class, 'update'])->name('update');
    Route::post('/delete/{id}', [StationController::class, 'destroy'])->name('destroy');
});

Route::group(['prefix' => 'trips','as'=>'trips.'], function () {
    Route::get('/', [TripController::class, 'index'])->name('index');
    Route::post('/list', [TripController::class, 'list'])->name('list');
    Route::get('/create', [TripController::class, 'create'])->name('create');
    Route::get('/show/{id}', [TripController::class, 'show'])->name('show');
    Route::get('/edit/{id}', [TripController::class, 'edit'])->name('edit');

    Route::post('/store', [TripController::class, 'store'])->name('store');
    Route::post('/update/{id}', [TripController::class, 'update'])->name('update');
    Route::post('/delete/{id}', [TripController::class, 'destroy'])->name('destroy');
});

Route::group(['prefix' => 'companies','as'=>'companies.'], function () {
    Route::get('/', [CompanyController::class, 'index'])->name('index');
    Route::post('/list', [CompanyController::class, 'list'])->name('list');
    Route::get('/create', [CompanyController::class, 'create'])->name('create');
    Route::get('/show/{id}', [CompanyController::class, 'show'])->name('show');
    Route::get('/edit/{id}', [CompanyController::class, 'edit'])->name('edit');

    Route::post('/store', [CompanyController::class, 'store'])->name('store');
    Route::post('/update/{id}', [CompanyController::class, 'update'])->name('update');
    Route::post('/delete/{id}', [CompanyController::class, 'destroy'])->name('destroy');
});

Route::group(['prefix' => 'screens','as'=>'screens.'], function () {
    Route::get('/', [ScreenController::class, 'index'])->name('index');
    Route::post('/list', [ScreenController::class, 'list'])->name('list');
    Route::get('/create', [ScreenController::class, 'create'])->name('create');
    Route::get('/show/{id}', [ScreenController::class, 'show'])->name('show');
    Route::get('/edit/{id}', [ScreenController::class, 'edit'])->name('edit');

    Route::post('/store', [ScreenController::class, 'store'])->name('store');
    Route::post('/update/{id}', [ScreenController::class, 'update'])->name('update');
    Route::post('/delete/{id}', [ScreenController::class, 'destroy'])->name('destroy');
});

app/Http/Controllers/Api/TripController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Models\User;
use App\Models\Trip;
use App\Models\TripUpdate;
use Illuminate\Http\Request;
use JWTAuth;
use Validator;

class TripController extends Controller
{ 
    public function getTrips(Request $request)
    {
        $user = auth()->user();
        $identityNumber = $user->identityNumber;
 
        $trips = Trip::with('tripupdates')->whereRaw('(primaryDriver = "'.$identityNumber.'" or assistantDriver = "'.$identityNumber.'"  )')->where('trip_status','!=','ENDED')->get();

        $success = [
                'success' => true,
                'message' => 'Trips get succcessfully',
                'data' => $trips
        ];
        return $this->sendResponse($success);
    }


    public function ChangeTripsStatus(Request $request)
    {
        $user = auth()->user();
        $identityNumber = $user->identityNumber;
        
        $validator = Validator::make($request->all(), [
            'trip_id' => 'required', 
        ]);

        if($validator->fails()){
            $errors = $validator->errors();
            foreach($errors->all() as $key=>$error){
                if($key == 0)
                    $message = $error;
            }
            $success = [
                'message' => $message,
                'success' => false
            ];
            return $this->sendResponse($success);
            //return $this->sendError($validator->errors());       
        }

        $trip = Trip::whereRaw('(primaryDriver = "'.$identityNumber.'" or assistantDriver = "'.$identityNumber.'"  )')->find($request->trip_id);

        if($trip){
			
			$trip_data = ["driverId"=> $identityNumber,"numberOfPassengersIn" => (int)$request->numberOfPassengersIn,"numberOfPassengersOut" => (int)$request->numberOfPassengersOut,"tripStatus" => $request->tripStatus,"currentStationCode" => $request->currentStationCode,"tripUpdateDateTime" => \Carbon\Carbon::now()->format('Y-m-d\TH:i:s.z\Z'),"activity" => $request->activity];
			$json_data = json_encode($trip_data);
			
			$curl = curl_init();
			curl_setopt_array($curl, array(
			  CURLOPT_URL => 'https://wasl.tga.gov.sa/api/tracking/v1/operating-companies/'.$trip->companyId.'/bus-trips/'.$trip->tripNumber,
			  CURLOPT_RETURNTRANSFER => true,
			  CURLOPT_ENCODING => '',
			  CURLOPT_MAXREDIRS => 10,
			  CURLOPT_TIMEOUT => 0,
			  CURLOPT_FOLLOWLOCATION => true,
			  CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
			  CURLOPT_CUSTOMREQUEST => 'PATCH',
			  CURLOPT_POSTFIELDS => $json_data,
			  CURLOPT_HTTPHEADER => array(
				'x-api-key: 1190c6bb-ea86-4302-bcbb-e426a279ce0b',
				'Content-Type: application/json'
			  ),
			));

			$response = curl_exec($curl);

			curl_close($curl);

			$result = json_decode($response);
			if(isset($result->errorCode) && $result->errorCode == "bad_request"){
				$success = [
                    'success' => false,
                    'message' => $result->errorMsg,
				];
				return $this->sendResponse($success);
			}
			if(isset($result->success) && $result->success == false)
			{	
				$success = [
                    'success' => false,
                    'message' => str_replace("_"," ",$result->resultCode),
				];
				return $this->sendResponse($success);
			}
			if($result->success){
				$tripupdate = new TripUpdate();
				$tripupdate->trip_id = $request->trip_id;
				$tripupdate->driverId = $identityNumber;
				$tripupdate->numberOfPassengersIn = $request->numberOfPassengersIn;
				$tripupdate->numberOfPassengersOut = $request->numberOfPassengersOut;
				$tripupdate->tripStatus = $request->tripStatus;
				$tripupdate->currentStationCode = $request->currentStationCode;
				$tripupdate->tripUpdateDateTime = \Carbon\Carbon::now()->format('Y-m-d\TH:i:s.z\Z');
				$tripupdate->activity = $request->activity;
				$tripupdate->wasl_response = $response;
				$tripupdate->save();
				
				$trip->update(['trip_status'=>$request->tripStatus]);
				$success = [
                    'success' => true,
                    'message' => 'Trip updated succcessfully',
                    'data' => $tripupdate
				];
			} else {
				$success = [
                    'success' => false,
                    'message' => 'wasl response failed'
				];
			}
            return $this->sendResponse($success);
        }

        $success = [
                    'success' => false,
                    'message' => 'Something went wrong'
        ];
        return $this->sendResponse($success);
    }
}

app/Http/Controllers/TripController.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use App\Models\User;
use App\Models\Trip;
use App\Models\Vehicle;
use App\Models\Station;
use App\Models\Companies;
use Illuminate\Http\Request;
use Yajra\DataTables\DataTables;
use Exception;

class TripController extends Controller
{

    public function index() {
        return view('trips.index');
    }

    
    public function list(DataTables $datatables,Request $request) {
        // $user = auth()->user();
        $query = \DB::table('trips');
        /*if(!empty($user->region) && strtolower($user->region) != 'all') {
            $query->whereRaw('(region) = ?',["{$user->region}"]);
        }
        if(!empty($user->territory) && strtolower($user->territory) != 'all') {
            $query->whereRaw('(territory) = ?',["{$user->territory}"]);
        }*/
        // return $datatables->eloquent(HCP::query())
        return   $datatables->of($query)
            ->addColumn('action',function ($table) {
                return view('tables.action',['table'=>$table,'prefix'=>'trips']);
            })
            ->rawColumns(['action'])
            ->toJson();
    }



    public function create()
    {
        $drivers = User::where('urole','driver')->select('identityNumber')->get();
        $vehicles = Vehicle::get();
        $stations = Station::get();

        $tripTypes = config('constants.tripTypes');
        $companies = Companies::get();
        $activities = config('constants.activities');
        return view('trips.create', compact('tripTypes','stations','vehicles','companies','activities','drivers'));
    }

    public function store(Request $request)
    {
        $data = $this->getData($request);
        try {
			$data['expectedDepartureTime'] = str_replace('+00:00', '.000Z', gmdate('c', (strtotime($data['expectedDepartureTime'])+10800)));
			$data['expectedArrivalTime'] = str_replace('+00:00', '.000Z', gmdate('c', (strtotime($data['expectedArrivalTime'])+10800)));
			
			$trip_data = ["vehicle"=> $data['vehicle'],"primaryDriver" => $data['primaryDriver'],"assistantDriver"=> $data['assistantDriver'],"tripNumber"=> $data['tripNumber'],"expectedDepartureTime"=> $data['expectedDepartureTime'],"expectedArrivalTime"=> $data['expectedArrivalTime'],"distanceInMeters"=> $data['distanceInMeters'],"tripType"=> $data['type'],"activity"=> $data['activity'],"departureStationCode"=> $data['departureStationCode'],"arrivalStationCode"=> $data['arrivalStationCode'],"numberOfPassengers"=> $data['numberOfPassengers']];
			$json_data = json_encode($trip_data);
			
			$curl = curl_init();

			curl_setopt_array($curl, array(
			  CURLOPT_URL => 'https://wasl.tga.gov.sa/api/tracking/v1/operating-companies/'.$data["companyId"].'/bus-trips',
			  CURLOPT_RETURNTRANSFER => true,
			  CURLOPT_ENCODING => '',
			  CURLOPT_MAXREDIRS => 10,
			  CURLOPT_TIMEOUT => 0,
			  CURLOPT_FOLLOWLOCATION => true,
			  CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
			  CURLOPT_CUSTOMREQUEST => 'POST',
			  CURLOPT_POSTFIELDS => $json_data,
			  CURLOPT_HTTPHEADER => array(
				'x-api-key: 1190c6bb-ea86-4302-bcbb-e426a279ce0b',
				'Content-Type: application/json'
			  ),
			));

			$response = curl_exec($curl);

			curl_close($curl);
			$result = json_decode($response);
			if(isset($result->errorCode) && $result->errorCode == "bad_request"){
				return back()->withInput()->withErrors(['unexpected_error' => $result->errorMsg]);
			}
			if(isset($result->success) && $result->success == false){
				return back()->withInput()
                         ->withErrors(['unexpected_error' => str_replace("_"," ",$result->resultCode)]);
			}
			if($result->success){
				$data['wasl_response'] = $response;
				Trip::create($data);

				return redirect()->route('trips.index')->with('success_message', 'Trip was successfully added.');
			} else {
				return back()->withInput()->withErrors(['unexpected_error' => 'Unexpected error occurred while trying to process your request.']);
			}
        } catch (Exception $exception) {
            return back()->withInput()->withErrors(['unexpected_error' => 'Unexpected error occurred while trying to process your request.']);
        }
    }

    /**
     * Display the specified labor item.
     *
     * @param int $id
     *
     * @return Illuminate\View\View
     */
    public function show($id)
    {
        $trip = Trip::findOrFail($id);

        return view('trips.show', compact('trip'));
    }

    /**
     * Show the form for editing the specified labor item.
     *
     * @param int $id
     *
     * @return Illuminate\View\View
     */
    public function edit($id)
    {   
        $trip =  Trip::findOrFail($id);
        $vehicles =  Vehicle::get();
        $stations =  Station::get();
        $drivers = User::where('urole','driver')->select('identityNumber')->get();
        $companies = Companies::get();
        $activities = config('constants.activities');
        $tripTypes = config('constants.tripTypes');
        return view('trips.edit', compact('trip','tripTypes','stations','vehicles','drivers','companies','activities'));
    }

    /**
     * Update the specified labor item in the storage.
     *
     * @param  int $id
     * @param Illuminate\Http\Request $request
     *
     * @return Illuminate\Http\RedirectResponse | Illuminate\Routing\Redirector
     */
    public function update($id, Request $request)
    {
        $data = $this->getData($request);
        try {
            $vehicle =  Trip::findOrFail($id);
            $vehicle->update($data);

            return redirect()->route('trips.index')
                             ->with('success_message', 'Trip was successfully updated.');

        } catch (Exception $exception) {

            return back()->withInput()
                         ->withErrors(['unexpected_error' => 'Unexpected error occurred while trying to process your request.']);
        }
    }

    /**
     * Remove the specified labor item from the storage.
     *
     * @param  int $id
     *
     * @return Illuminate\Http\RedirectResponse | Illuminate\Routing\Redirector
     */
    public function destroy($id)
    {
        try {
            $vehicle = Trip::findOrFail($id);
            $vehicle->delete();

            return redirect()->route('trips.index')
                             ->with('success_message', 'Trip was successfully deleted.');

        } catch (Exception $exception) {

            return back()->withInput()
                         ->withErrors(['unexpected_error' => 'Unexpected error occurred while trying to process your request.']);
        }
    }


    /**
     * Get the request's data from the request.
     *
     * @param Illuminate\Http\Request\Request $request
     * @return array
     */
    protected function getData(Request $request)
    {
        $rules = [
            "vehicle"=> 'required',
            "primaryDriver"=> 'required',
            "assistantDriver"=> 'required',
            "tripNumber"=> 'required',
            "expectedDepartureTime"=> 'required',
            "expectedArrivalTime"=> 'required',
            "distanceInMeters"=> 'required',
            "numberOfPassengers"=> 'required',
            "type"=> 'required',
            "activity"=> 'required',
            "departureStationCode"=> 'required',
            "arrivalStationCode"=> 'required',
            "companyId"=> 'required',
        ];
        $data = $request->validate($rules);
        
        return $data;
    }

}

resources/views/trips/create.blade.php
@extends('layouts.master')
@section('content')
<div class="container-fluid">
	<div class="row">
		<div class="col-lg-12">
			<div class="breadcrumb-main user-member justify-content-sm-between ">
				<div class=" d-flex flex-wrap justify-content-center breadcrumb-main__wrapper">
					<div class="d-flex align-items-center user-member__title justify-content-center mr-sm-25">
						<h4 class="text-capitalize fw-500 breadcrumb-title">Add Trip</h4>
					</div>
				</div>
				 <div class="action-btn">
                        <a href="{{ route('trips.index') }}" class="btn px-15 btn-primary" >Cancel</a>
                 </div>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-lg-12">
			<!-- Start: product page -->
			<div class="global-shadow border px-sm-30 py-sm-50 px-0 py-20 bg-white radius-xl w-100 mb-40">
				<div class="row  ">
					<div class="col-xl-12 col-lg-10">
						<div class="mx-sm-30 mx-20 ">
							<!-- Start: card -->
							<!-- <div class="card add-product p-sm-30 p-20 mb-30">
									<div class="card-body p-0">
										<div class="card-header">
											<h6 class="fw-500">Add Product</h6>
										</div> -->
										<!-- Start: card body -->
										<div class="add-product__body px-sm-40 px-20">
											<form method="POST" action="{{ route('trips.store') }}" accept-charset="UTF-8" id="create_user_form" name="create_user_form" class="form-horizontal" enctype="multipart/form-data">
													{{ csrf_field() }}
													@include ('trips.form', ['trip' => null])
											</form>
										</div>
								<!-- </div>
							</div> -->
					
						</div>
					</div>
				</div>
			</div>
			<!-- End: Product page -->
		</div>
		<!-- ends: col-lg-12 -->
	</div>
</div>
@endsection
 @push('css')
	<link rel="stylesheet" href="/libraries/assets/vendor_assets/css/line-awesome.min.css">
	 <link rel="stylesheet" href="/css/daterangepicker.css">
	 <style type="text/css">
	 		.daterangepicker  .ranges{
	 			display: none !important;
	 		}
	 		.daterangepicker.single .calendar-table tbody td.today, .daterangepicker.single .calendar-table tbody td.active {
	 			color: #5f63f2 !important;
	 		}
	 		.daterangepicker.show-calendar .calendar-table tbody td.available.active.end-date:before {
	 			display: none !important;
	 		}
	 		.daterangepicker.show-calendar .calendar-table tbody td.available.active.start-date:after, 
	 		.daterangepicker.show-calendar .calendar-table tbody td.available.active.start-date:before,
	 		.daterangepicker.show-calendar .calendar-table tbody td.available.active.end-date:after,
	 		.daterangepicker.show-calendar .calendar-table tbody td.available.active.end-date:before,
	 		.daterangepicker.show-calendar .calendar-table tbody td.today,
	 		.daterangepicker.show-calendar .calendar-table tbody td.today:after {
	 			    border-radius: 6px !important;
	 		} 

	 		.drp-buttons  {
	 			display: flex!important;
	 		}
	 		.drp-buttons .btn-sm {
	 			    line-height: 1.5rem !important;
	 		}
	 		.daterangepicker .calendar-time {
	 			margin-top: 20px;
	 		}
			.daterangepicker select.hourselect, .daterangepicker select.minuteselect, .daterangepicker select.secondselect, .daterangepicker select.ampmselect
	 		{
	 			    font-size: 14px;
				    padding: 4px 10px;
				    width: 70px;
				    background: #fff;
	 		}
	 		.daterangepicker.single .drp-calendar.left {
			    padding: 0 20px 2px;
			}
	 </style>
 @endpush
 @push('scripts')
  	<!-- <script src="/libraries/assets/vendor_assets/js/jquery/jquery-ui.js"></script> -->
 		<script src="/js/daterangepicker.js"></script>

<script >
 
  $( document ).ready(function() {
	  $('.start_time').daterangepicker({
    	timePicker: true,
	    singleDatePicker: true,
	    autoUpdateInput: false,
	    timePicker24Hour:true,
	    locale: {
	      format: 'YYYY-MM-DD HH:mm'
	    }
	  }, function(start, end, label) {
	  		$('.start_time').val(start.format('YYYY-MM-DD HH:mm'))
		});


	  $(".end_time").daterangepicker({
    	timePicker: true,
	    singleDatePicker: true,
	    autoUpdateInput: false,
	    timePicker24Hour:true,
	    locale: {
	      format: 'YYYY-MM-DD HH:mm'
	    }
	  }, function(start, end, label) {
		  		$('.end_time').val(start.format('YYYY-MM-DD HH:mm'))
		});
  });
 </script>

 @endpush

resources/views/trips/edit.blade.php
@extends('layouts.master')
@section('content')
<div class="container-fluid">
	<div class="row">
		<div class="col-lg-12">
			<div class="breadcrumb-main user-member justify-content-sm-between ">
				<div class=" d-flex flex-wrap justify-content-center breadcrumb-main__wrapper">
					<div class="d-flex align-items-center user-member__title justify-content-center mr-sm-25">
						<h4 class="text-capitalize fw-500 breadcrumb-title">Edit Trip</h4>
					</div>
				</div>
				 <div class="action-btn">
                        <a href="{{ route('trips.index') }}" class="btn px-15 btn-primary" >Cancel</a>
                 </div>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-lg-12">
			<!-- Start: product page -->
			<div class="global-shadow border px-sm-30 py-sm-50 px-0 py-20 bg-white radius-xl w-100 mb-40">
				<div class="row  ">
					<div class="col-xl-12 col-lg-10">
						<div class="mx-sm-30 mx-20 ">
							<!-- Start: card -->
							<!-- <div class="card add-product p-sm-30 p-20 mb-30">
									<div class="card-body p-0">
										<div class="card-header">
											<h6 class="fw-500">Add Product</h6>
										</div> -->
										<!-- Start: card body -->
										<div class="add-product__body px-sm-40 px-20">
											<form method="POST" action="{{ route('trips.update',$trip->id) }}" accept-charset="UTF-8" id="create_user_form" name="create_user_form" class="form-horizontal" enctype="multipart/form-data">
													{{ csrf_field() }}
													@include ('trips.form', ['trips' => $trip])
											</form>
										</div>
								<!-- </div>
							</div> -->
					
						</div>
					</div>
				</div>
			</div>
			<!-- End: Product page -->
		</div>
		<!-- ends: col-lg-12 -->
	</div>
</div>
@endsection
@push('css')
	<link rel="stylesheet" href="/libraries/assets/vendor_assets/css/line-awesome.min.css">
	 <link rel="stylesheet" href="/css/daterangepicker.css">
	 <style type="text/css">
	 		.daterangepicker  .ranges{
	 			display: none !important;
	 		}
	 		.daterangepicker.single .calendar-table tbody td.today, .daterangepicker.single .calendar-table tbody td.active {
	 			color: #5f63f2 !important;
	 		}
	 		.daterangepicker.show-calendar .calendar-table tbody td.available.active.end-date:before {
	 			display: none !important;
	 		}
	 		.daterangepicker.show-calendar .calendar-table tbody td.available.active.start-date:after, 
	 		.daterangepicker.show-calendar .calendar-table tbody td.available.active.start-date:before,
	 		.daterangepicker.show-calendar .calendar-table tbody td.available.active.end-date:after,
	 		.daterangepicker.show-calendar .calendar-table tbody td.available.active.end-date:before,
	 		.daterangepicker.show-calendar .calendar-table tbody td.today,
	 		.daterangepicker.show-calendar .calendar-table tbody td.today:after {
	 			    border-radius: 6px !important;
	 		} 

	 		.drp-buttons  {
	 			display: flex!important;
	 		}
	 		.drp-buttons .btn-sm {
	 			    line-height: 1.5rem !important;
	 		}
	 		.daterangepicker .calendar-time {
	 			margin-top: 20px;
	 		}
			.daterangepicker select.hourselect, .daterangepicker select.minuteselect, .daterangepicker select.secondselect, .daterangepicker select.ampmselect
	 		{
	 			    font-size: 14px;
				    padding: 4px 10px;
				    width: 70px;
				    background: #fff;
	 		}
	 		.daterangepicker.single .drp-calendar.left {
			    padding: 0 20px 2px;
			}
	 </style>
 @endpush
 @push('scripts')
 		<script src="/js/daterangepicker.js"></script>
<script >
 
  $( document ).ready(function() {
	  $('.start_time').daterangepicker({
    	timePicker: true,
	    singleDatePicker: true,
	    autoUpdateInput: false,
	    timePicker24Hour:true,
	     locale: {
	      format: 'YYYY-MM-DD HH:mm'
	    }
	  }, function(start, end, label) {
	  		$('.start_time').val(start.format('YYYY-MM-DD HH:mm'))
		});


	  $(".end_time").daterangepicker({
    	timePicker: true,
	    singleDatePicker: true,
	    autoUpdateInput: false,
	    timePicker24Hour:true,
	     locale: {
	      format: 'YYYY-MM-DD HH:mm'
	    }
	  }, function(start, end, label) {
		  		$('.end_time').val(start.format('YYYY-MM-DD HH:mm'))
		});
  });
 </script>

 @endpush