routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\DriverController;
use App\Http\Controllers\VehicleController;
use App\Http\Controllers\StationController;
use App\Http\Controllers\TripController;
use App\Http\Controllers\CompanyController;
use App\Http\Controllers\ScreenController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes(['register' => false]);

Route::get('/import', [App\Http\Controllers\ImportController::class, 'uploadContent']);
Route::get('/dashboard', [App\Http\Controllers\HomeController::class, 'index'])->name('dashboard');

 


Route::group(['prefix' => 'driver','as'=>'driver.'], function () {
    Route::get('/', [DriverController::class, 'index'])->name('index');
    Route::post('/list', [DriverController::class, 'list'])->name('list');
    Route::get('/create', [DriverController::class, 'create'])->name('create');
    Route::get('/show/{id}', [DriverController::class, 'show'])->name('show');
    Route::get('/edit/{id}', [DriverController::class, 'edit'])->name('edit');

    Route::post('/store', [DriverController::class, 'store'])->name('store');
    Route::post('/update/{id}', [DriverController::class, 'update'])->name('update');
    Route::post('/delete/{id}', [DriverController::class, 'destroy'])->name('destroy');
    
});

Route::group(['prefix' => 'vehicles','as'=>'vehicles.'], function () {
    Route::get('/', [VehicleController::class, 'index'])->name('index');
    Route::post('/list', [VehicleController::class, 'list'])->name('list');
    Route::get('/create', [VehicleController::class, 'create'])->name('create');
    Route::get('/show/{id}', [VehicleController::class, 'show'])->name('show');
    Route::get('/edit/{id}', [VehicleController::class, 'edit'])->name('edit');

    Route::post('/store', [VehicleController::class, 'store'])->name('store');
    Route::post('/update/{id}', [VehicleController::class, 'update'])->name('update');
    Route::post('/delete/{id}', [VehicleController::class, 'destroy'])->name('destroy');
});

Route::group(['prefix' => 'stations','as'=>'stations.'], function () {
    Route::get('/', [StationController::class, 'index'])->name('index');
    Route::post('/list', [StationController::class, 'list'])->name('list');
    Route::get('/create', [StationController::class, 'create'])->name('create');
    Route::get('/show/{id}', [StationController::class, 'show'])->name('show');
    Route::get('/edit/{id}', [StationController::class, 'edit'])->name('edit');

    Route::post('/store', [StationController::class, 'store'])->name('store');
    Route::post('/update/{id}', [StationController::class, 'update'])->name('update');
    Route::post('/delete/{id}', [StationController::class, 'destroy'])->name('destroy');
});

Route::group(['prefix' => 'trips','as'=>'trips.'], function () {
    Route::get('/', [TripController::class, 'index'])->name('index');
    Route::post('/list', [TripController::class, 'list'])->name('list');
    Route::get('/create', [TripController::class, 'create'])->name('create');
    Route::get('/show/{id}', [TripController::class, 'show'])->name('show');
    Route::get('/edit/{id}', [TripController::class, 'edit'])->name('edit');

    Route::post('/store', [TripController::class, 'store'])->name('store');
    Route::post('/update/{id}', [TripController::class, 'update'])->name('update');
    Route::post('/delete/{id}', [TripController::class, 'destroy'])->name('destroy');
});

Route::group(['prefix' => 'companies','as'=>'companies.'], function () {
    Route::get('/', [CompanyController::class, 'index'])->name('index');
    Route::post('/list', [CompanyController::class, 'list'])->name('list');
    Route::get('/create', [CompanyController::class, 'create'])->name('create');
    Route::get('/show/{id}', [CompanyController::class, 'show'])->name('show');
    Route::get('/edit/{id}', [CompanyController::class, 'edit'])->name('edit');

    Route::post('/store', [CompanyController::class, 'store'])->name('store');
    Route::post('/update/{id}', [CompanyController::class, 'update'])->name('update');
    Route::post('/delete/{id}', [CompanyController::class, 'destroy'])->name('destroy');
});

Route::group(['prefix' => 'screens','as'=>'screens.'], function () {
    Route::get('/', [ScreenController::class, 'index'])->name('index');
    Route::post('/list', [ScreenController::class, 'list'])->name('list');
    Route::get('/create', [ScreenController::class, 'create'])->name('create');
    Route::get('/show/{id}', [ScreenController::class, 'show'])->name('show');
    Route::get('/edit/{id}', [ScreenController::class, 'edit'])->name('edit');

    Route::post('/store', [ScreenController::class, 'store'])->name('store');
    Route::post('/update/{id}', [ScreenController::class, 'update'])->name('update');
    Route::post('/delete/{id}', [ScreenController::class, 'destroy'])->name('destroy');
});

app/Models/Vehicle.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Vehicle extends Model
{
    use HasFactory;


    protected $fillable = [
        'waslDriverId',
        'waslCompanyId',
        'gpsGateUserId',
        'gpsGateServerId',
        'sequenceNumber',
        'plateType',
        'plateNumber',
        'plateRightLetter',
        'plateMiddleLetter',
        'plateLeftLetter',
        'imeiNumber',
        'waslActivity',
    ];
}

app/Http/Controllers/VehicleController.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use App\Models\User;
use App\Models\Vehicle;
use App\Models\Companies;
use Illuminate\Http\Request;
use Yajra\DataTables\DataTables;
use Exception;

class VehicleController extends Controller
{

    public function index()
    {
        return view('vehicles.index');
    }

    
    public function list(DataTables $datatables,Request $request){
        // $user = auth()->user();
        $query = \DB::table('vehicles');
        /*if(!empty($user->region) && strtolower($user->region) != 'all') {
            $query->whereRaw('(region) = ?',["{$user->region}"]);
        }
        if(!empty($user->territory) && strtolower($user->territory) != 'all') {
            $query->whereRaw('(territory) = ?',["{$user->territory}"]);
        }*/
        // return $datatables->eloquent(HCP::query())
        return   $datatables->of($query)
            ->addColumn('action',function ($table) {
                return view('tables.action',['table'=>$table,'prefix'=>'vehicles']);
            })
            ->rawColumns(['action'])
            ->toJson();
    }



    public function create()
    {
        $drivers = User::where('urole','driver')->select('id','identityNumber')->get();
        $companies = Companies::get();
        $activities = config('constants.activities');
        return view('vehicles.create', compact('companies','activities','drivers'));
    }

    public function store(Request $request)
    {
        $data = $this->getData($request);
        try {
          
           Vehicle::create($data);

            return redirect()->route('vehicles.index')
                             ->with('success_message', 'Labor Item was successfully added.');

        } catch (Exception $exception) {

            return back()->withInput()
                         ->withErrors(['unexpected_error' => 'Unexpected error occurred while trying to process your request.']);
        }
    }

    /**
     * Display the specified labor item.
     *
     * @param int $id
     *
     * @return Illuminate\View\View
     */
    public function show($id)
    {
        $vehicle = Vehicle::findOrFail($id);

        return view('vehicles.show', compact('vehicle'));
    }

    /**
     * Show the form for editing the specified labor item.
     *
     * @param int $id
     *
     * @return Illuminate\View\View
     */
    public function edit($id)
    {   
        $vehicle =  Vehicle::findOrFail($id);
        $drivers = User::where('urole','driver')->select('id','identityNumber')->get();
        $companies = Companies::get();
        $activities = config('constants.activities');
        return view('vehicles.edit', compact('vehicle','drivers','companies','activities'));
    }

    /**
     * Update the specified labor item in the storage.
     *
     * @param  int $id
     * @param Illuminate\Http\Request $request
     *
     * @return Illuminate\Http\RedirectResponse | Illuminate\Routing\Redirector
     */
    public function update($id, Request $request)
    {
        $data = $this->getData($request);
        try {
            $vehicle =  Vehicle::findOrFail($id);
            $vehicle->update($data);

            return redirect()->route('vehicles.index')
                             ->with('success_message', 'Labor Item was successfully updated.');

        } catch (Exception $exception) {

            return back()->withInput()
                         ->withErrors(['unexpected_error' => 'Unexpected error occurred while trying to process your request.']);
        }
    }

    /**
     * Remove the specified labor item from the storage.
     *
     * @param  int $id
     *
     * @return Illuminate\Http\RedirectResponse | Illuminate\Routing\Redirector
     */
    public function destroy($id)
    {
        try {
            $vehicle = Vehicle::findOrFail($id);
            $vehicle->delete();

            return redirect()->route('vehicles.index')
                             ->with('success_message', 'Labor Item was successfully deleted.');

        } catch (Exception $exception) {

            return back()->withInput()
                         ->withErrors(['unexpected_error' => 'Unexpected error occurred while trying to process your request.']);
        }
    }


    /**
     * Get the request's data from the request.
     *
     * @param Illuminate\Http\Request\Request $request
     * @return array
     */
    protected function getData(Request $request)
    {
        $rules = [
            'waslDriverId' => 'required',
            'waslCompanyId' => 'required',
            'gpsGateUserId' => 'required',
            'gpsGateServerId' => 'required',
            'sequenceNumber' => 'required',
            'plateType' => 'required',
            'plateNumber' => 'required',
            'plateRightLetter' => 'required',
            'plateMiddleLetter' => 'required',
            'plateLeftLetter' => 'required',
            'imeiNumber' => 'required',
            'waslActivity' => 'required',
        ];
        $data = $request->validate($rules);
        
        return $data;
    }

}

resources/views/vehicles/create.blade.php
@extends('layouts.master')
@section('content')
<div class="container-fluid">
	<div class="row">
		<div class="col-lg-12">
			<div class="breadcrumb-main user-member justify-content-sm-between ">
				<div class=" d-flex flex-wrap justify-content-center breadcrumb-main__wrapper">
					<div class="d-flex align-items-center user-member__title justify-content-center mr-sm-25">
						<h4 class="text-capitalize fw-500 breadcrumb-title">Add Vehicle</h4>
					</div>
				</div>
				 <div class="action-btn">
                        <a href="{{ route('vehicles.index') }}" class="btn px-15 btn-primary" >Cancel</a>
                 </div>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-lg-12">
			<!-- Start: product page -->
			<div class="global-shadow border px-sm-30 py-sm-50 px-0 py-20 bg-white radius-xl w-100 mb-40">
				<div class="row  ">
					<div class="col-xl-12 col-lg-10">
						<div class="mx-sm-30 mx-20 ">
							<!-- Start: card -->
							<!-- <div class="card add-product p-sm-30 p-20 mb-30">
									<div class="card-body p-0">
										<div class="card-header">
											<h6 class="fw-500">Add Product</h6>
										</div> -->
										<!-- Start: card body -->
										<div class="add-product__body px-sm-40 px-20">
											<form method="POST" action="{{ route('vehicles.store') }}" accept-charset="UTF-8" id="create_user_form" name="create_user_form" class="form-horizontal" enctype="multipart/form-data">
													{{ csrf_field() }}
													@include ('vehicles.form', ['vehicle' => null])
											</form>
										</div>
								<!-- </div>
							</div> -->
					
						</div>
					</div>
				</div>
			</div>
			<!-- End: Product page -->
		</div>
		<!-- ends: col-lg-12 -->
	</div>
</div>
@endsection

resources/views/vehicles/edit.blade.php
@extends('layouts.master')
@section('content')
<div class="container-fluid">
	<div class="row">
		<div class="col-lg-12">
			<div class="breadcrumb-main user-member justify-content-sm-between ">
				<div class=" d-flex flex-wrap justify-content-center breadcrumb-main__wrapper">
					<div class="d-flex align-items-center user-member__title justify-content-center mr-sm-25">
						<h4 class="text-capitalize fw-500 breadcrumb-title">Edit Vehicle</h4>
					</div>
				</div>
				 <div class="action-btn">
                        <a href="{{ route('vehicles.index') }}" class="btn px-15 btn-primary" >Cancel</a>
                 </div>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-lg-12">
			<!-- Start: product page -->
			<div class="global-shadow border px-sm-30 py-sm-50 px-0 py-20 bg-white radius-xl w-100 mb-40">
				<div class="row  ">
					<div class="col-xl-12 col-lg-10">
						<div class="mx-sm-30 mx-20 ">
				 
							<div class="add-product__body px-sm-40 px-20">
								<form method="POST" action="{{ route('vehicles.update',$vehicle->id) }}" accept-charset="UTF-8" id="create_user_form" name="create_user_form" class="form-horizontal" enctype="multipart/form-data">
										{{ csrf_field() }}
										@include ('vehicles.form', ['vehicle' => $vehicle])
								</form>
							</div>
				 
					
						</div>
					</div>
				</div>
			</div>
			<!-- End: Product page -->
		</div>
		<!-- ends: col-lg-12 -->
	</div>
</div>
@endsection

resources/views/vehicles/form.blade.php
<div class="form-basic">
    <div class="col-md-12" id="message">
        @if ($message = Session::get('error'))
        <div class="alert alert-danger">
          <p>{{ $message }}</p>
        </div>
        @endif
    </div>  
		@error('unexpected_error')
			<span class="invalid-feedback" role="alert">
				<strong>{{ $message }}</strong>
			</span>
		@enderror
	 
	<div class="form-group">
		<div class="countryOption">
			<label for="countryOption">
				wasl Driver Id
			</label>
			<select class="js-example-basic-single js-states form-control" id="waslDriverId" name="waslDriverId" >
				<option value="" style="display:none;">Select Wasl Driver Id</option>
                @foreach ($drivers as $driver)
                    <option value="{{ $driver->identityNumber }}"  {{ ( $driver->identityNumber == old('waslDriverId', optional($vehicle)->waslDriverId)) ? 'selected' : '' }}>{{$driver->identityNumber}}</option>
                @endforeach
			</select>
			@error('waslDriverId')
				<span class="invalid-feedback" role="alert">
					<strong>{{ $message }}</strong>
				</span>
			@enderror
		</div>
	</div>

	<div class="form-group">
		<div class="countryOption">
			<label for="countryOption">wasl Company Id</label> 
			<select class="js-example-basic-single js-states form-control" id="waslCompanyId" name="waslCompanyId" >
				<option value="" style="display:none;">Select Wasl Company Id</option>
                @foreach ($companies as $value)
                    <option value="{{ $value->companyId }}"  {{ ( $value->companyId == old('waslCompanyId',optional($vehicle)->waslCompanyId) )? 'selected' : '' }}>{{$value->companyName}}</option>
                @endforeach
			</select>
			@error('waslCompanyId')
				<span class="invalid-feedback" role="alert">
					<strong>{{ $message }}</strong>
				</span>
			@enderror
		</div>
	</div>

	<div class="form-group">
		<label for="name1">gps Gate User Id</label>
		<input type="text" id="gpsGateUserId" name="gpsGateUserId" class="form-control" placeholder="Enter gps Gate User Id" value="{{old('gpsGateUserId', optional($vehicle)->gpsGateUserId)}}" > 
		@error('gpsGateUserId')
			<span class="invalid-feedback" role="alert">
				<strong>{{ $message }}</strong>
			</span>
		@enderror
	</div> 


	<div class="form-group">
		<div class="countryOption">
			<label for="countryOption">
				gps Gate Server Id
			</label>
			<select class="js-example-basic-single js-states form-control" id="gpsGateServerId" name="gpsGateServerId" >
				<option value="" style="display:none;">Select gps Gate Server Id</option>
                <option value="1"  {{ ( 1 == old('gpsGateServerId', optional($vehicle)->gpsGateServerId)) ? 'selected' : '' }}>1</option>
                <option value="2"  {{ ( 2 == old('gpsGateServerId', optional($vehicle)->gpsGateServerId)) ? 'selected' : '' }}>2</option>
                <option value="3"  {{ ( 3 == old('gpsGateServerId', optional($vehicle)->gpsGateServerId)) ? 'selected' : '' }}>3</option>
                <option value="4"  {{ ( 4 == old('gpsGateServerId', optional($vehicle)->gpsGateServerId)) ? 'selected' : '' }}>4</option>
                <option value="5"  {{ ( 5 == old('gpsGateServerId', optional($vehicle)->gpsGateServerId)) ? 'selected' : '' }}>5</option>
                <option value="6"  {{ ( 6 == old('gpsGateServerId', optional($vehicle)->gpsGateServerId)) ? 'selected' : '' }}>6</option>
                <option value="7"  {{ ( 7 == old('gpsGateServerId', optional($vehicle)->gpsGateServerId)) ? 'selected' : '' }}>7</option>
                <option value="8"  {{ ( 8 == old('gpsGateServerId', optional($vehicle)->gpsGateServerId)) ? 'selected' : '' }}>8</option>
			</select>
			@error('gpsGateServerId')
				<span class="invalid-feedback" role="alert">
					<strong>{{ $message }}</strong>
				</span>
			@enderror
		</div>
	</div>
 

	<div class="form-group">
		<label for="name1">Sequence Number</label>
		<input type="text" id="sequenceNumber" name="sequenceNumber" class="form-control" placeholder="Enter sequence Number" value="{{old('sequenceNumber', optional($vehicle)->sequenceNumber)}}" > 
		@error('sequenceNumber')
			<span class="invalid-feedback" role="alert">
				<strong>{{ $message }}</strong>
			</span>
		@enderror
	</div> 
 
 

	<div class="form-group">
		<label for="name1">Plate Type</label>
		<input type="text" id="plateType" name="plateType" class="form-control" placeholder="Enter plate Type" value="{{old('plateType', optional($vehicle)->plateType)}}" > 
		@error('plateType')
			<span class="invalid-feedback" role="alert">
				<strong>{{ $message }}</strong>
			</span>
		@enderror
	</div>  
 
 

	<div class="form-group">
		<label for="name1">Plate Number</label>
		<input type="text" id="plateNumber" name="plateNumber" class="form-control" placeholder="Enter plate Number" value="{{old('plateNumber', optional($vehicle)->plateNumber)}}" > 
		@error('plateNumber')
			<span class="invalid-feedback" role="alert">
				<strong>{{ $message }}</strong>
			</span>
		@enderror
	</div>  
 
 


	<div class="form-group">
		<label for="name1">Plate Right Letter</label>
		<input type="text" id="plateRightLetter" name="plateRightLetter" class="form-control" placeholder="Enter plate Right Letter" value="{{old('plateRightLetter', optional($vehicle)->plateRightLetter)}}" > 
		@error('plateRightLetter')
			<span class="invalid-feedback" role="alert">
				<strong>{{ $message }}</strong>
			</span>
		@enderror
	</div>  
 


	<div class="form-group">
		<label for="name1">Plate Middle Letter</label>
		<input type="text" id="plateMiddleLetter" name="plateMiddleLetter" class="form-control" placeholder="Enter plate Middle Letter" value="{{old('plateMiddleLetter', optional($vehicle)->plateMiddleLetter)}}" > 
		@error('plateMiddleLetter')
			<span class="invalid-feedback" role="alert">
				<strong>{{ $message }}</strong>
			</span>
		@enderror
	</div>  
 

	<div class="form-group">
		<label for="name1">Plate Left Letter</label>
		<input type="text" id="plateLeftLetter" name="plateLeftLetter" class="form-control" placeholder="Enter plate Left Letter" value="{{old('plateLeftLetter', optional($vehicle)->plateLeftLetter)}}" > 
		@error('plateLeftLetter')
			<span class="invalid-feedback" role="alert">
				<strong>{{ $message }}</strong>
			</span>
		@enderror
	</div>  
 
 
	<div class="form-group">
		<label for="name1">imei Number</label>
		<input type="text" id="imeiNumber" name="imeiNumber" class="form-control" placeholder="Enter imei Number" value="{{old('imeiNumber', optional($vehicle)->imeiNumber)}}" > 
		@error('imeiNumber')
			<span class="invalid-feedback" role="alert">
				<strong>{{ $message }}</strong>
			</span>
		@enderror
	</div>  
 
	<div class="form-group">
		<div class="countryOption">
			<label for="countryOption">
				wasl Activity
			</label>
			<select class="js-example-basic-single js-states form-control" id="waslActivity" name="waslActivity" >
				<option value="" style="display:none;">Select Wasl Activity</option>
                @foreach ($activities as $value)
                    <option value="{{ $value->code }}"  {{ ( $value->code ==  old('waslActivity', optional($vehicle)->waslActivity) ) ? 'selected' : '' }}>{{$value->english_name}}</option>
                @endforeach
			</select>
			@error('waslActivity')
				<span class="invalid-feedback" role="alert">
					<strong>{{ $message }}</strong>
				</span>
			@enderror
		</div>
	</div>
 

	<!-- Start: button group -->
	<div class="button-group add-product-btn d-flex justify-content-end mt-40">
		<button class="btn btn-light btn-default btn-squared fw-400 text-capitalize"> <a  href="{{ route('vehicles.index') }}"> cancel</a></button>
		<button class="btn btn-primary btn-default btn-squared text-capitalize">Save</button>
	</div>
	<!-- End: button group -->
</div>

resources/views/vehicles/show.blade.php
@extends('layouts.master')
@section('content')
<div class="container-fluid">
	<div class="row">
		<div class="col-lg-12">
			<div class="breadcrumb-main user-member justify-content-sm-between ">
				<div class=" d-flex flex-wrap justify-content-center breadcrumb-main__wrapper">
					<div class="d-flex align-items-center user-member__title justify-content-center mr-sm-25">
						<h4 class="text-capitalize fw-500 breadcrumb-title">Driver Detail</h4>
					</div>
				</div>
				 <div class="action-btn">
                <a href="{{ route('driver.index') }}" class="btn px-15 btn-primary" >Driver List</a>
         </div>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-lg-12">
			<!-- Start: product page -->
			<div class="global-shadow border px-sm-15 py-sm-30 px-0 py-20 bg-white radius-xl w-100 mb-40">
				<div class="row  ">
					<div class="col-xl-12 col-lg-10">
						<div class="mx-sm-30 mx-20 ">
					 
							<div class=" "> 

								 <div class="div mb-3">
				                    <h6>Wasl Driver Id</h6>
				                    <span>{{ $vehicle->waslDriverId }}</span>
				                </div>

								 <div class="div mb-3">
				                    <h6>Wasl Company Id</h6>
				                    <span>{{ $vehicle->waslCompanyId }}</span>
				                </div>

								 <div class="div mb-3">
				                    <h6>Gps Gate User Id</h6>
				                    <span>{{ $vehicle->gpsGateUserId }}</span>
				                </div>

								 <div class="div mb-3">
				                    <h6>Gps Gate Server Id</h6>
				                    <span>{{ $vehicle->gpsGateServerId }}</span>
				                </div>

								 <div class="div mb-3">
				                    <h6>Sequence Number</h6>
				                    <span>{{ $vehicle->sequenceNumber }}</span>
				                </div>

								 <div class="div mb-3">
				                    <h6>Plate Type</h6>
				                    <span>{{ $vehicle->plateType }}</span>
				                </div>

								 <div class="div mb-3">
				                    <h6>Plate Number</h6>
				                    <span>{{ $vehicle->plateNumber }}</span>
				                </div>

								 <div class="div mb-3">
				                    <h6>Plate Right Letter</h6>
				                    <span>{{ $vehicle->plateRightLetter }}</span>
				                </div>

								 <div class="div mb-3">
				                    <h6>Plate Middle Letter</h6>
				                    <span>{{ $vehicle->plateMiddleLetter }}</span>
				                </div>

								 <div class="div mb-3">
				                    <h6>Plate Left Letter</h6>
				                    <span>{{ $vehicle->plateLeftLetter }}</span>
				                </div>

								 <div class="div mb-3">
				                    <h6>Imei Number</h6>
				                    <span>{{ $vehicle->imeiNumber }}</span>
				                </div>

								 <div class="div mb-3">
				                    <h6>Wasl Activity</h6>
				                    <span>{{ $vehicle->waslActivity }}</span>
				                </div>
						 
							</div>
							 
					
						</div>
					</div>
				</div>
			</div>
			<!-- End: Product page -->
		</div>
		<!-- ends: col-lg-12 -->
	</div>
</div>
@endsection

 