routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\DriverController;
use App\Http\Controllers\VehicleController;
use App\Http\Controllers\StationController;
use App\Http\Controllers\TripController;
use App\Http\Controllers\CompanyController;
use App\Http\Controllers\ScreenController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes(['register' => false]);

Route::get('/import', [App\Http\Controllers\ImportController::class, 'uploadContent']);
Route::get('/dashboard', [App\Http\Controllers\HomeController::class, 'index'])->name('dashboard');

 


Route::group(['prefix' => 'driver','as'=>'driver.'], function () {
    Route::get('/', [DriverController::class, 'index'])->name('index');
    Route::post('/list', [DriverController::class, 'list'])->name('list');
    Route::get('/create', [DriverController::class, 'create'])->name('create');
    Route::get('/show/{id}', [DriverController::class, 'show'])->name('show');
    Route::get('/edit/{id}', [DriverController::class, 'edit'])->name('edit');

    Route::post('/store', [DriverController::class, 'store'])->name('store');
    Route::post('/update/{id}', [DriverController::class, 'update'])->name('update');
    Route::post('/delete/{id}', [DriverController::class, 'destroy'])->name('destroy');
    
});

Route::group(['prefix' => 'vehicles','as'=>'vehicles.'], function () {
    Route::get('/', [VehicleController::class, 'index'])->name('index');
    Route::post('/list', [VehicleController::class, 'list'])->name('list');
    Route::get('/create', [VehicleController::class, 'create'])->name('create');
    Route::get('/show/{id}', [VehicleController::class, 'show'])->name('show');
    Route::get('/edit/{id}', [VehicleController::class, 'edit'])->name('edit');

    Route::post('/store', [VehicleController::class, 'store'])->name('store');
    Route::post('/update/{id}', [VehicleController::class, 'update'])->name('update');
    Route::post('/delete/{id}', [VehicleController::class, 'destroy'])->name('destroy');
});

Route::group(['prefix' => 'stations','as'=>'stations.'], function () {
    Route::get('/', [StationController::class, 'index'])->name('index');
    Route::post('/list', [StationController::class, 'list'])->name('list');
    Route::get('/create', [StationController::class, 'create'])->name('create');
    Route::get('/show/{id}', [StationController::class, 'show'])->name('show');
    Route::get('/edit/{id}', [StationController::class, 'edit'])->name('edit');

    Route::post('/store', [StationController::class, 'store'])->name('store');
    Route::post('/update/{id}', [StationController::class, 'update'])->name('update');
    Route::post('/delete/{id}', [StationController::class, 'destroy'])->name('destroy');
});

Route::group(['prefix' => 'trips','as'=>'trips.'], function () {
    Route::get('/', [TripController::class, 'index'])->name('index');
    Route::post('/list', [TripController::class, 'list'])->name('list');
    Route::get('/create', [TripController::class, 'create'])->name('create');
    Route::get('/show/{id}', [TripController::class, 'show'])->name('show');
    Route::get('/edit/{id}', [TripController::class, 'edit'])->name('edit');

    Route::post('/store', [TripController::class, 'store'])->name('store');
    Route::post('/update/{id}', [TripController::class, 'update'])->name('update');
    Route::post('/delete/{id}', [TripController::class, 'destroy'])->name('destroy');
});

Route::group(['prefix' => 'companies','as'=>'companies.'], function () {
    Route::get('/', [CompanyController::class, 'index'])->name('index');
    Route::post('/list', [CompanyController::class, 'list'])->name('list');
    Route::get('/create', [CompanyController::class, 'create'])->name('create');
    Route::get('/show/{id}', [CompanyController::class, 'show'])->name('show');
    Route::get('/edit/{id}', [CompanyController::class, 'edit'])->name('edit');

    Route::post('/store', [CompanyController::class, 'store'])->name('store');
    Route::post('/update/{id}', [CompanyController::class, 'update'])->name('update');
    Route::post('/delete/{id}', [CompanyController::class, 'destroy'])->name('destroy');
});

Route::group(['prefix' => 'screens','as'=>'screens.'], function () {
    Route::get('/', [ScreenController::class, 'index'])->name('index');
    Route::post('/list', [ScreenController::class, 'list'])->name('list');
    Route::get('/create', [ScreenController::class, 'create'])->name('create');
    Route::get('/show/{id}', [ScreenController::class, 'show'])->name('show');
    Route::get('/edit/{id}', [ScreenController::class, 'edit'])->name('edit');

    Route::post('/store', [ScreenController::class, 'store'])->name('store');
    Route::post('/update/{id}', [ScreenController::class, 'update'])->name('update');
    Route::post('/delete/{id}', [ScreenController::class, 'destroy'])->name('destroy');
});

app/Http/Controllers/CompanyController.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use App\Models\Companies;
use Illuminate\Http\Request;
use Yajra\DataTables\DataTables;
use Exception;

class CompanyController extends Controller
{

    public function index() {
        return view('companies.index');
    }

    
    public function list(DataTables $datatables,Request $request) {

        $query = \DB::table('companies');
        return   $datatables->of($query)
            ->addColumn('action',function ($table) {
                return view('tables.action',['table'=>$table,'prefix'=>'companies']);
            })
            ->rawColumns(['action'])
            ->toJson();
    }



    public function create()
    {
        return view('companies.create');
    }

    public function store(Request $request)
    {
        $data = $this->getData($request);
        $company_data = ["companyName"=> $data['companyName'],"companyId" => $data['companyId']];
        
        Companies::create($data);

        return redirect()->route('companies.index')->with('success_message', 'Company was successfully added.');
    }

    /**
     * Display the specified labor item.
     *
     * @param int $id
     *
     * @return Illuminate\View\View
     */
    public function show($id)
    {
        $companies = Companies::findOrFail($id);
        return view('companies.show', compact('companies'));
    }

    /**
     * Show the form for editing the specified labor item.
     *
     * @param int $id
     *
     * @return Illuminate\View\View
     */
    public function edit($id)
    {   
        $companies =  Companies::findOrFail($id);
        return view('companies.edit', compact('companies'));
    }

    /**
     * Update the specified labor item in the storage.
     *
     * @param  int $id
     * @param Illuminate\Http\Request $request
     *
     * @return Illuminate\Http\RedirectResponse | Illuminate\Routing\Redirector
     */
    public function update($id, Request $request)
    {
        $data = $this->getData($request);
        try {
            $vehicle =  Companies::findOrFail($id);
            $vehicle->update($data);

            return redirect()->route('companies.index')
                             ->with('success_message', 'Companies was successfully updated.');

        } catch (Exception $exception) {

            return back()->withInput()
                         ->withErrors(['unexpected_error' => 'Unexpected error occurred while trying to process your request.']);
        }
    }

    /**
     * Remove the specified labor item from the storage.
     *
     * @param  int $id
     *
     * @return Illuminate\Http\RedirectResponse | Illuminate\Routing\Redirector
     */
    public function destroy($id)
    {
        try {
            $vehicle = Companies::findOrFail($id);
            $vehicle->delete();

            return redirect()->route('companies.index')
                             ->with('success_message', 'Companies was successfully deleted.');

        } catch (Exception $exception) {

            return back()->withInput()
                         ->withErrors(['unexpected_error' => 'Unexpected error occurred while trying to process your request.']);
        }
    }


    /**
     * Get the request's data from the request.
     *
     * @param Illuminate\Http\Request\Request $request
     * @return array
     */
    protected function getData(Request $request)
    {
        $rules = [
            "companyName"=> 'required',
            "companyId"=> 'required',
        ];
        $data = $request->validate($rules);
        
        return $data;
    }

}

resources/views/companies/create.blade.php
@extends('layouts.master')
@section('content')
<div class="container-fluid">
	<div class="row">
		<div class="col-lg-12">
			<div class="breadcrumb-main user-member justify-content-sm-between ">
				<div class=" d-flex flex-wrap justify-content-center breadcrumb-main__wrapper">
					<div class="d-flex align-items-center user-member__title justify-content-center mr-sm-25">
						<h4 class="text-capitalize fw-500 breadcrumb-title">Add Company</h4>
					</div>
				</div>
				 <div class="action-btn">
                        <a href="{{ route('companies.index') }}" class="btn px-15 btn-primary" >Cancel</a>
                 </div>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-lg-12">
			<!-- Start: product page -->
			<div class="global-shadow border px-sm-30 py-sm-50 px-0 py-20 bg-white radius-xl w-100 mb-40">
				<div class="row  ">
					<div class="col-xl-12 col-lg-10">
						<div class="mx-sm-30 mx-20 ">
							<!-- Start: card -->
							<!-- <div class="card add-product p-sm-30 p-20 mb-30">
									<div class="card-body p-0">
										<div class="card-header">
											<h6 class="fw-500">Add Product</h6>
										</div> -->
										<!-- Start: card body -->
										<div class="add-product__body px-sm-40 px-20">
											<form method="POST" action="{{ route('companies.store') }}" accept-charset="UTF-8" id="create_user_form" name="create_user_form" class="form-horizontal" enctype="multipart/form-data">
													{{ csrf_field() }}
													@include ('companies.form', ['companies' => null])
											</form>
										</div>
								<!-- </div>
							</div> -->
					
						</div>
					</div>
				</div>
			</div>
			<!-- End: Product page -->
		</div>
		<!-- ends: col-lg-12 -->
	</div>
</div>
@endsection
 @push('css')
	<link rel="stylesheet" href="/libraries/assets/vendor_assets/css/line-awesome.min.css">
	 <link rel="stylesheet" href="/css/daterangepicker.css">
	 <style type="text/css">
	 		.daterangepicker  .ranges{
	 			display: none !important;
	 		}
	 		.daterangepicker.single .calendar-table tbody td.today, .daterangepicker.single .calendar-table tbody td.active {
	 			color: #5f63f2 !important;
	 		}
	 		.daterangepicker.show-calendar .calendar-table tbody td.available.active.end-date:before {
	 			display: none !important;
	 		}
	 		.daterangepicker.show-calendar .calendar-table tbody td.available.active.start-date:after, 
	 		.daterangepicker.show-calendar .calendar-table tbody td.available.active.start-date:before,
	 		.daterangepicker.show-calendar .calendar-table tbody td.available.active.end-date:after,
	 		.daterangepicker.show-calendar .calendar-table tbody td.available.active.end-date:before,
	 		.daterangepicker.show-calendar .calendar-table tbody td.today,
	 		.daterangepicker.show-calendar .calendar-table tbody td.today:after {
	 			    border-radius: 6px !important;
	 		} 

	 		.drp-buttons  {
	 			display: flex!important;
	 		}
	 		.drp-buttons .btn-sm {
	 			    line-height: 1.5rem !important;
	 		}
	 		.daterangepicker .calendar-time {
	 			margin-top: 20px;
	 		}
			.daterangepicker select.hourselect, .daterangepicker select.minuteselect, .daterangepicker select.secondselect, .daterangepicker select.ampmselect
	 		{
	 			    font-size: 14px;
				    padding: 4px 10px;
				    width: 70px;
				    background: #fff;
	 		}
	 		.daterangepicker.single .drp-calendar.left {
			    padding: 0 20px 2px;
			}
	 </style>
 @endpush
 @push('scripts')
  	<!-- <script src="/libraries/assets/vendor_assets/js/jquery/jquery-ui.js"></script> -->
 		<script src="/js/daterangepicker.js"></script>

<script >
 
  $( document ).ready(function() {
	  $('.start_time').daterangepicker({
    	timePicker: true,
	    singleDatePicker: true,
	    autoUpdateInput: false,
	    timePicker24Hour:true,
	    locale: {
	      format: 'YYYY-MM-DD HH:mm'
	    }
	  }, function(start, end, label) {
	  		$('.start_time').val(start.format('YYYY-MM-DD HH:mm'))
		});


	  $(".end_time").daterangepicker({
    	timePicker: true,
	    singleDatePicker: true,
	    autoUpdateInput: false,
	    timePicker24Hour:true,
	    locale: {
	      format: 'YYYY-MM-DD HH:mm'
	    }
	  }, function(start, end, label) {
		  		$('.end_time').val(start.format('YYYY-MM-DD HH:mm'))
		});
  });
 </script>

 @endpush

resources/views/companies/edit.blade.php
@extends('layouts.master')
@section('content')
<div class="container-fluid">
	<div class="row">
		<div class="col-lg-12">
			<div class="breadcrumb-main user-member justify-content-sm-between ">
				<div class=" d-flex flex-wrap justify-content-center breadcrumb-main__wrapper">
					<div class="d-flex align-items-center user-member__title justify-content-center mr-sm-25">
						<h4 class="text-capitalize fw-500 breadcrumb-title">Edit Company</h4>
					</div>
				</div>
				 <div class="action-btn">
                        <a href="{{ route('companies.index') }}" class="btn px-15 btn-primary" >Cancel</a>
                 </div>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-lg-12">
			<!-- Start: product page -->
			<div class="global-shadow border px-sm-30 py-sm-50 px-0 py-20 bg-white radius-xl w-100 mb-40">
				<div class="row  ">
					<div class="col-xl-12 col-lg-10">
						<div class="mx-sm-30 mx-20 ">
							<!-- Start: card -->
							<!-- <div class="card add-product p-sm-30 p-20 mb-30">
									<div class="card-body p-0">
										<div class="card-header">
											<h6 class="fw-500">Add Product</h6>
										</div> -->
										<!-- Start: card body -->
										<div class="add-product__body px-sm-40 px-20">
											<form method="POST" action="{{ route('companies.update',$companies->id) }}" accept-charset="UTF-8" id="create_user_form" name="create_user_form" class="form-horizontal" enctype="multipart/form-data">
													{{ csrf_field() }}
													@include ('companies.form', ['companies' => $companies])
											</form>
										</div>
								<!-- </div>
							</div> -->
					
						</div>
					</div>
				</div>
			</div>
			<!-- End: Product page -->
		</div>
		<!-- ends: col-lg-12 -->
	</div>
</div>
@endsection
@push('css')
	<link rel="stylesheet" href="/libraries/assets/vendor_assets/css/line-awesome.min.css">
	 <link rel="stylesheet" href="/css/daterangepicker.css">
	 <style type="text/css">
	 		.daterangepicker  .ranges{
	 			display: none !important;
	 		}
	 		.daterangepicker.single .calendar-table tbody td.today, .daterangepicker.single .calendar-table tbody td.active {
	 			color: #5f63f2 !important;
	 		}
	 		.daterangepicker.show-calendar .calendar-table tbody td.available.active.end-date:before {
	 			display: none !important;
	 		}
	 		.daterangepicker.show-calendar .calendar-table tbody td.available.active.start-date:after, 
	 		.daterangepicker.show-calendar .calendar-table tbody td.available.active.start-date:before,
	 		.daterangepicker.show-calendar .calendar-table tbody td.available.active.end-date:after,
	 		.daterangepicker.show-calendar .calendar-table tbody td.available.active.end-date:before,
	 		.daterangepicker.show-calendar .calendar-table tbody td.today,
	 		.daterangepicker.show-calendar .calendar-table tbody td.today:after {
	 			    border-radius: 6px !important;
	 		} 

	 		.drp-buttons  {
	 			display: flex!important;
	 		}
	 		.drp-buttons .btn-sm {
	 			    line-height: 1.5rem !important;
	 		}
	 		.daterangepicker .calendar-time {
	 			margin-top: 20px;
	 		}
			.daterangepicker select.hourselect, .daterangepicker select.minuteselect, .daterangepicker select.secondselect, .daterangepicker select.ampmselect
	 		{
	 			    font-size: 14px;
				    padding: 4px 10px;
				    width: 70px;
				    background: #fff;
	 		}
	 		.daterangepicker.single .drp-calendar.left {
			    padding: 0 20px 2px;
			}
	 </style>
 @endpush
 @push('scripts')
 		<script src="/js/daterangepicker.js"></script>
<script >
 
  $( document ).ready(function() {
	  $('.start_time').daterangepicker({
    	timePicker: true,
	    singleDatePicker: true,
	    autoUpdateInput: false,
	    timePicker24Hour:true,
	     locale: {
	      format: 'YYYY-MM-DD HH:mm'
	    }
	  }, function(start, end, label) {
	  		$('.start_time').val(start.format('YYYY-MM-DD HH:mm'))
		});


	  $(".end_time").daterangepicker({
    	timePicker: true,
	    singleDatePicker: true,
	    autoUpdateInput: false,
	    timePicker24Hour:true,
	     locale: {
	      format: 'YYYY-MM-DD HH:mm'
	    }
	  }, function(start, end, label) {
		  		$('.end_time').val(start.format('YYYY-MM-DD HH:mm'))
		});
  });
 </script>

 @endpush

resources/views/companies/form.blade.php
<div class="form-basic">
    <div class="col-md-12" id="message">
        @if ($message = Session::get('error'))
        <div class="alert alert-danger">
          <p>{{ $message }}</p>
        </div>
        @endif
    </div>  
	@error('unexpected_error')
		<span class="invalid-feedback" role="alert">
			<strong>{{ $message }}</strong>
		</span>
	@enderror

	<div class="form-group">
		<label for="name1">Company Name</label>
		<input type="text" id="companyname" name="companyName" class="form-control" placeholder="Enter Company Name" value="{{old('companyName', optional($companies)->companyName)}}" > 
		@error('companyname')
			<span class="invalid-feedback" role="alert">
				<strong>{{ $message }}</strong>
			</span>
		@enderror
	</div> 

	<div class="form-group">
		<label for="name1">Company Id</label>
		<input type="text" id="companyid" name="companyId" class="form-control" placeholder="Enter Company Id" value="{{old('companyId', optional($companies)->companyId)}}" > 
		@error('companyid')
			<span class="invalid-feedback" role="alert">
				<strong>{{ $message }}</strong>
			</span>
		@enderror
	</div> 

	<!-- Start: button group -->
	<div class="button-group add-product-btn d-flex justify-content-end mt-40">
		<button class="btn btn-light btn-default btn-squared fw-400 text-capitalize"> <a  href="{{ route('companies.index') }}"> cancel</a></button>
		<button class="btn btn-primary btn-default btn-squared text-capitalize">Save</button>
	</div>
	<!-- End: button group -->
</div>

resources/views/companies/index.blade.php
@extends('layouts.master')
@section('content')
<div class="container-fluid">
	<div class="row">
		<div class="col-lg-12">
			<div class="breadcrumb-main user-member justify-content-sm-between ">
				<div class=" d-flex flex-wrap justify-content-center breadcrumb-main__wrapper">
					<div class="d-flex align-items-center user-member__title justify-content-center mr-sm-25">
						<h4 class="text-capitalize fw-500 breadcrumb-title">List Company</h4>
					</div>
				</div>
				<div style="display: flex;">
					<div class="action-btn">
						<a href="{{route('companies.create')}}" class="btn px-15 btn-primary" >
							<i class="las la-plus fs-16"></i>Add New Company</a> 
					</div>
			    </div>
			</div>

		</div>
	</div>
	<div class="row">
		<div class="col-lg-12">
			<div class="userDatatable global-shadow border p-30 bg-white radius-xl w-100 mb-30">
				<div class="col-md-12">
					@if ($message = Session::get('success'))
					<div class="alert alert-success mt-2 mb-2">
					  <p>{{ $message }}</p>
					</div>
					@endif
				</div>
				<div class="table-responsive">
					<table id="datatabled" class="table mb-0 table-borderless">
						<thead>
							<tr class="userDatatable-header">
                  <th>
                      <span class="userDatatable-title">Id</span>
                  </th>

                  <th>
                      <span class="userDatatable-title">Company Name</span>
                  </th>

                  <th>
                      <span class="userDatatable-title">Company Id</span>
                  </th>

                  <th>
                      <span class="userDatatable-title"></span>
                  </th>
							</tr>
						</thead>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>
 
<form action="" method="POST" class="remove-record-form">
    <div class="modal fade" id="DeleteRecordmodal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog  modal-sm" role="document">
        <div class="modal-content">
          <div class="modal-body">
            <p></p>
            <h4>Are You Sure?</h4>
            <p>Delete This Record?</p>
          </div>
          <div class="modal-footer">
            <button type="submit" class="btn btn-primary waves-effect waves-light">Yes, Delete it!</button>
            <button type="button" class="btn btn-default waves-effect remove-data-from-delete-form" data-dismiss="modal">No Cancel!</button>
          </div>
        </div>
      </div>
    </div>
</form>
@endsection
@push('css')
 <!-- dataTable CSS -->
<link href="{{asset('js/datatables/jquery.dataTables.min.css')}}" rel="stylesheet" type="text/css" />
<link href="https://cdn.datatables.net/buttons/1.4.2/css/buttons.dataTables.min.css" rel="stylesheet">
@endpush

@push('scripts')
<script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.4.2/js/dataTables.buttons.min.js"></script>
<script src="//cdn.datatables.net/buttons/1.4.2/js/buttons.flash.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.32/pdfmake.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.32/vfs_fonts.js"></script>
<script src="//cdn.datatables.net/buttons/1.4.2/js/buttons.html5.min.js"></script>
<script src="//cdn.datatables.net/buttons/1.4.2/js/buttons.print.min.js"></script>
<script src="//cdn.datatables.net/buttons/1.4.2/js/buttons.colVis.min.js"></script>
    <script>
         $(document).ready(function () {
          
            $('#datatabled').DataTable({
                // "scrollX": true,
                orderCellsTop: true,
                fixedHeader: true,
                dom: 'frtlp',
                language: {
                    "search": '',
                    "searchPlaceholder": "Search..."
                },
                order: [[0, "asc"]],
                serverSide: true,
                processing: true,
                 "ajax": {
                    "url": "{{url('companies/list')}}",
                    "type": "POST"
                },
                columns: [
                    {data: 'id'},
                    {data: 'companyName'},
                    {data: 'companyId'},
                    {data: 'action', orderable: false, searchable: false}
                ],
                columnDefs: [ 
                    {
                        "width": "100px",
                        "targets": 0
                    }
                ]
            });
            $('.dataTables_filter input').attr('class','form-control input-lg');
            $('.dataTables_filter input').attr('aria-describedby','search-addon');
            $('.dataTables_filter input').wrap( '<div class="input-group form-material"></div>' );
            $('.dataTables_length select').addClass('form-control input-sm');
        });
    </script>
@endpush

resources/views/companies/show.blade.php
@extends('layouts.master')
@section('content')
<div class="container-fluid">
	<div class="row">
		<div class="col-lg-12">
			<div class="breadcrumb-main user-member justify-content-sm-between ">
				<div class=" d-flex flex-wrap justify-content-center breadcrumb-main__wrapper">
					<div class="d-flex align-items-center user-member__title justify-content-center mr-sm-25">
						<h4 class="text-capitalize fw-500 breadcrumb-title">Company Detail</h4>
					</div>
				</div>
				<div class="action-btn">
                	<a href="{{ route('companies.index') }}" class="btn px-15 btn-primary" >Company List</a>
         		</div>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-lg-12">
			<!-- Start: product page -->
			<div class="global-shadow border px-sm-15 py-sm-30 px-0 py-20 bg-white radius-xl w-100 mb-40">
				<div class="row  ">
					<div class="col-xl-6 col-lg-6">
						<div class="mx-sm-30 mx-20 ">
					 
							<div class=" "> 

								<div class="div mb-3">
				                    <h6>Id</h6>
				                    <span>{{ $companies->id }}</span>
				                </div> 
						  
								<div class="div mb-3">
				                    <h6>Company Name</h6>
				                    <span>{{ $companies->companyName }}</span>
				                </div> 
						  
								<div class="div mb-3">
				                    <h6>Company Id</h6>
				                    <span>{{ $companies->companyId }}</span>
				                </div> 
						  
							</div>
							 
						</div>
					</div>
				</div>
			</div>
			<!-- End: Product page -->
		</div>
		<!-- ends: col-lg-12 -->
	</div>
</div>
@endsection

 